### ISSUE TITLE
Swagger invoice endpoint issue

### ISSUE THREAD

**Issue by fieryorc** [killbill/killbill#940]
Thanks for fixing the swagger issues. Invoices endpoint has couple of issues:

- path param "locale" is not present in path "/1.0/kb/invoices/manualPayTemplate"

- path /1.0/kb/invoices/{invoiceId} overlaps with /1.0/kb/invoices/{invoiceNumber}

**Comment by sbrossie** [comment]
```
  /1.0/kb/invoices/manualPayTemplate:
    get:
      tags:
      - "Invoice"
      summary: "Retrieves the manualPay invoice template for the tenant"
      description: ""
      operationId: "getInvoiceMPTemplate"
      produces:
      - "text/html"
      parameters:
      - name: "locale"
        in: "path"
        required: true
        type: "string"
```
